# Generated by Django 5.2.1 on 2025-10-07 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_seed_data'),
    ]

    operations = [
    ]
